image: node:8

# Set up MySQL test-database
services:
  - mysql:5.5

# Configure test-database
variables:
  MYSQL_DATABASE: supertestdb
  MYSQL_ROOT_PASSWORD: secret

# Install node libraries

# Run JEST tests
run_tests:
  stage: test
  script:
    - cd server && npm install && npm test && npm run flow
    - cd ../klient && npm install && npm test && npm run flow
    - cd ../socket && npm install && npm run flow
  artifacts:
    paths:
      - server/coverage/
